# View OSM Output for `Austin`

Expects a directory with a fully parsed dataset result.

In [1]:
from IPython.display import display

import rasterio as rio          # 1.2.4
import geopandas as gpd         # 0.9.0
import shapely.geometry as shp  # 1.7.1 

# Both have CRS:  espg:4326
raster = rio.open('data/osm-sets/tuscaloosa_01/tuscaloosa_01.tif')
roads = gpd.read_file('data/osm-sets/tuscaloosa_01/roads.shp')

# Convert raster bounds to shape
bbox = shp.box(*raster.bounds)
bbox = gpd.GeoSeries(bbox, crs=roads.crs)
display(roads)

clipped_roads = gpd.clip(roads, bbox)

clipped_roads.to_file('data/tests/tuscaloosa/clipped_roads.shp')

,index,category,label,name,geometry
0,0,None,residential,Monte Vista Circle,"LINESTRING (-87.48667 33.16766, -87.48682 33.1..."
1,1,None,residential,Monte Vista Circle,"LINESTRING (-87.48664 33.16682, -87.48666 33.1..."
2,2,None,residential,Caplewood Drive,"LINESTRING (-87.55477 33.21429, -87.55483 33.2..."
3,3,None,residential,Hamilton Lane,"LINESTRING (-87.51621 33.18704, -87.51615 33.1..."
4,4,None,residential,Hamilton Lane,"LINESTRING (-87.51495 33.18708, -87.51538 33.1..."
...,...,...,...,...,...
8178,26632,None,service,None,"LINESTRING (-87.55294 33.21255, -87.55276 33.2..."
8179,26633,None,service,None,"LINESTRING (-87.55265 33.21268, -87.55263 33.2..."
8180,26634,None,service,None,"LINESTRING (-87.55250 33.21332, -87.55240 33.2..."
8181,26635,None,service,None,"LINESTRING (-87.55222 33.21324, -87.55226 33.2..."
8182,26636,None,service,None,"LINESTRING (-87.55252 33.21263, -87.55249 33.2..."

,index,category,label,name,geometry
0,0,None,residential,Monte Vista Circle,"LINESTRING (-87.48667 33.16766, -87.48682 33.1..."
1,1,None,residential,Monte Vista Circle,"LINESTRING (-87.48664 33.16682, -87.48666 33.1..."
2,2,None,residential,Caplewood Drive,"LINESTRING (-87.55477 33.21429, -87.55483 33.2..."
3,3,None,residential,Hamilton Lane,"LINESTRING (-87.51621 33.18704, -87.51615 33.1..."
4,4,None,residential,Hamilton Lane,"LINESTRING (-87.51495 33.18708, -87.51538 33.1..."
...,...,...,...,...,...
8178,26632,None,service,None,"LINESTRING (-87.55294 33.21255, -87.55276 33.2..."
8179,26633,None,service,None,"LINESTRING (-87.55265 33.21268, -87.55263 33.2..."
8180,26634,None,service,None,"LINESTRING (-87.55250 33.21332, -87.55240 33.2..."
8181,26635,None,service,None,"LINESTRING (-87.55222 33.21324, -87.55226 33.2..."
8182,26636,None,service,None,"LINESTRING (-87.55252 33.21263, -87.55249 33.2..."

In [ ]:
import os
import lib.misc as m
import lib.geovisual as gv
root = './data/osm-sets'

set_name = 'austin'
set_folder = os.path.join(root, set_name)

if not os.path.exists(set_folder):
    raise RuntimeError(f"Passed set folder does not exist: '{set_folder}'. Check hyperparameters.")

## Inspect Raster Results

In [ ]:
import rasterio as rio
raster_fp = os.path.join(set_folder, set_name + ".tif")

with rio.open(raster_fp) as raster:
    m.print_header("Raster Info")
    print(f"- Width: {raster.width}")
    print(f"- Height: {raster.height}")
    print(f"- Bands: {raster.count}")
    print(f"- Scale: {raster.scales[0]}")
    print(f"- CRS: {raster.crs}")

## Building Analysis

In [ ]:
import geopandas as gpd
import shapely.geometry as shp

fp = os.path.join(set_folder, 'buildings.shp')
gdf = gpd.read_file(fp)
gv.gdf_overview(gdf, 'Building GDF')
values = gv.gdf_value_columns(gdf, [k for k in gdf.columns if k not in ['name', 'index', 'geometry']])

In [ ]:
import geopandas as gpd
import shapely.geometry as shp


fp = os.path.join(set_folder, 'roads.shp')
gdf = gpd.read_file(fp)
gv.gdf_overview(gdf, "Road GDF")
values = gv.gdf_value_columns(gdf, [k for k in gdf.columns if k not in ['name', 'index', 'geometry']])

In [ ]:
import geopandas as gpd
import shapely.geometry as shp

fp = os.path.join(set_folder, 'ungrouped.shp')
gdf = gpd.read_file(fp)
gv.gdf_overview(gdf, f"Ungrouped GDF")
values = gv.gdf_value_columns(gdf, [k for k in gdf.columns if k not in ['name', 'index', 'geometry']])